org.test.cloud.sandbox:
  application:
    context: "${APP_CONTEXT:}"
    port: "${APP_PORT:8080}"
  db:
    host: "${DB_HOST:localhost}"
    port: "${DB_PORT:8080}"
    context: "${DB_CONTEXT:/data}"
camel.springboot.main-run-controller: true
